
site_name: pyNotes
site_url: https://dzc0d3r.github.io/pynotes/

# Repository
repo_name: dzc0d3r/pynotes
repo_url: https://github.com/dzc0d3r/pynotes
theme:
  logo: assets/python.png
  favicon: assets/python.png
  name: material
  font: false
  features:
    - toc.follow 
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.indexes 
    - navigation.prune
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: indigo
      accent: blue
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
      primary: indigo
      accent: blue 
  
    


    


        
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde





plugins:
  - mkdocs-video:
      video_muted: True
      video_controls: True
  - search
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: suffix
      material_alternate: true
      default_language: en
      reconfigure_material: true
      languages:
          - locale: en
            name: English
            build: true
            default: true
            nav:
              - Welcome to the jungle : index.md
              - Getting started: 
                - Introduction to programming and programming languages : getting_started/introduction-to-programming.en.md
                - What is Python ? : getting_started/what-is-python.en.md
                - What do i need ? : getting_started/what-i-need.en.md
                - The zen of Python : getting_started/zen-of-python.en.md
              - Python Basics :
                - Your First App : python_basics/syntax-and-your-first-app.en.md
              - Python Intermediate:
                - Introduction : python_intermediate/introduction.en.md
              - Python Advanced:
                - Introduction : python_advanced/introduction.en.md
              - Python Tips:
                - Introduction : python_tips/introduction.en.md
          - locale: ar
            name: العربية
            build: true
            site_name: باينوتس
            nav:
              - Welcome to the jungle : index.ar.md
              - Getting started: 
                - Introduction to programming and programming languages : getting_started/introduction-to-programming.ar.md
                - What is Python ? : getting_started/what-is-python.ar.md
                - What do i need ? : getting_started/what-i-need.ar.md
                - The zen of Python : getting_started/zen-of-python.ar.md
              - Python Basics :
                - Your First App : python_basics/syntax-and-your-first-app.ar.md
              - Python Intermediate:
                - Introduction : python_intermediate/introduction.ar.md
              - Python Advanced:
                - Introduction : python_advanced/introduction.ar.md
              - Python Tips:
                - Introduction : python_tips/introduction.ar.md
            nav_translations:
                Getting started: إبدأ الآن
                Python Basics: أساسيّات لغة بايثون
                Python Intermediate: المستوى المتوسّط في البايثون
                Python Advanced: المستوى المتقدّم في بايثون
                Python Tips: نصائح في البايثون

                Introduction: مقدّمة
                Introduction to programming and programming languages: مقدّمة إلى البرمجة
                  ولغات البرمجة
                Python syntax: التركيب النحوي في لغة بايثون
                Comments in Python: التعليقات في لغة بايثون
                The zen of Python: زن البايثون
                Welcome to the jungle: مرحبا بك في الأدغال
                What do i need ?: ماذا أحتاج ؟
                What is Python ?: ما هي لغة البايثون؟
                Your First App: برنامجك الأول

              





            
          
        

     
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dzc0d3r
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/8990846/walid-lamraoui
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/walid-lamraoui/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dzc0d3r   

copyright: |
  &copy; 2023 <a href="https://github.com/dzc0d3r"  target="_blank" rel="noopener">Walid Lamraoui</a>